spring:
  jackson:
    time-zone: UTC

  datasource:
    url: jdbc:mysql://<your-mysql-host>:3306/<db_name>?useSSL=false&useUnicode=true&serverTimezone=UTC
    username: <usernmae>
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  logging:
    level:
      org.hibernate.SQL: debug